In [13]:
import pandas as pd
from preprocess import preprocess

In [14]:
df = pd.read_excel('data/ep2-pln-train.xlsx')
df.head()

                                            req_text age
0  - Quantos empregados em cada um dos atuais nív...  a2
1  - Solicito cópia das Atas do Conselho de Admin...  a2
2  - Solicito informar a norma (lei, decreto, por...  a2
3  - Solicito por gentileza, a informação sobre a...  a2
4  - Solicito por gentileza, a informação sobre a...  a2

In [15]:
preprocess.encode_class(df, 'age')
df.head()

                                            req_text age  age_encoded
0  - Quantos empregados em cada um dos atuais nív...  a2            1
1  - Solicito cópia das Atas do Conselho de Admin...  a2            1
2  - Solicito informar a norma (lei, decreto, por...  a2            1
3  - Solicito por gentileza, a informação sobre a...  a2            1
4  - Solicito por gentileza, a informação sobre a...  a2            1

In [16]:
preprocess.tokenize(df, 'req_text', True, True)
df.head()

,req_text,age,age_encoded,word_tokens
0,quantos empregados em cada um dos atuais níve...,a2,1,"[quantos, empregados, em, cada, um, dos, atuai..."
1,solicito cópia das atas do conselho de admini...,a2,1,"[solicito, cópia, das, atas, do, conselho, de,..."
2,solicito informar a norma lei decreto portari...,a2,1,"[solicito, informar, a, norma, lei, decreto, p..."
3,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, por, gentileza, a, informação, sobr..."
4,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, por, gentileza, a, informação, sobr..."

In [17]:
import nltk
from nltk.corpus import stopwords

In [18]:
#nltk.download('stopwords')

In [19]:
stop_words = set(stopwords.words('portuguese'))

In [20]:
temp = []

for text in df['word_tokens']:
    text = [w for w in text if not w.lower() in stop_words]
    temp.append(text)

df['word_tokens'] = temp
temp = []

df.head()

,req_text,age,age_encoded,word_tokens
0,quantos empregados em cada um dos atuais níve...,a2,1,"[quantos, empregados, cada, atuais, níveis, sa..."
1,solicito cópia das atas do conselho de admini...,a2,1,"[solicito, cópia, atas, conselho, administraçã..."
2,solicito informar a norma lei decreto portari...,a2,1,"[solicito, informar, norma, lei, decreto, port..."
3,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, gentileza, informação, sobre, quant..."
4,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, gentileza, informação, sobre, quant..."

considerar usar o lg news do spacy

In [21]:
preprocess.lemmatize(df, 'word_tokens', True)
df.head()

,req_text,age,age_encoded,word_tokens,lemma
0,quantos empregados em cada um dos atuais níve...,a2,1,"[quantos, empregados, cada, atuais, níveis, sa...",quanto empregado cada atual nível salarial pca...
1,solicito cópia das atas do conselho de admini...,a2,1,"[solicito, cópia, atas, conselho, administraçã...",solicito cópia ata conselho administração bnde...
2,solicito informar a norma lei decreto portari...,a2,1,"[solicito, informar, norma, lei, decreto, port...",solicito informar norma lei decreto portaria i...
3,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, gentileza, informação, sobre, quant...",solicito gentileza informação sobre quantidade...
4,solicito por gentileza a informação sobre a q...,a2,1,"[solicito, gentileza, informação, sobre, quant...",solicito gentileza informação sobre quantidade...

In [22]:
df.to_csv('data/enc_tok_nostopword_nopunct_lemm.csv')